# Generated by Django 2.0.2 on 2018-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
